import { TerraformStack } from "cdktf";
import { Construct } from "constructs";
import { join } from "path";
import { IamRole } from "../../.gen/providers/aws/iam-role";
import { IamRolePolicyAttachment } from "../../.gen/providers/aws/iam-role-policy-attachment";
import { LambdaFunction } from "../../.gen/providers/aws/lambda-function";
import { AwsProvider } from "../../.gen/providers/aws/provider";
import { DataNodeLambdaPackagerPackage } from "../../.gen/providers/node-lambda-packager/data-node-lambda-packager-package";
import { NodeLambdaPackagerProvider } from "../../.gen/providers/node-lambda-packager/provider";

export class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new AwsProvider(this, "AwsProvider");
    new NodeLambdaPackagerProvider(this, "NodeLambdaPackagerProvider");

    // IAM Role for Lambda
    const lambdaRole = new IamRole(this, "LambdaRole", {
      name: "lambda-role",
      assumeRolePolicy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "lambda.amazonaws.com",
            },
            Action: "sts:AssumeRole",
          },
        ],
      }),
    });

    // IAM Role Policy for Lambda
    new IamRolePolicyAttachment(this, "LambdaRolePolicyAttachment", {
      role: lambdaRole.name,
      policyArn:
        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    });

    // SampleLambda zipped package generated by esbuild
    const sampleLambdaPackage = new DataNodeLambdaPackagerPackage(
      this,
      "SampleLambdaPackage",
      {
        args: [
          "--bundle",
          "--minify",
          "--sourcemap",
          "--platform=node",
          "--target=es2024",
        ],
        entrypoint: join(__dirname, "..", "functions/sample", "index.ts"),
        workingDirectory: join(__dirname, "..", "functions/sample"),
      },
    );

    // SampleLambda function
    new LambdaFunction(this, "SampleLambda", {
      functionName: "sample-lambda",
      role: lambdaRole.arn,
      runtime: "nodejs22.x",
      filename: sampleLambdaPackage.filename,
      sourceCodeHash: sampleLambdaPackage.sourceCodeHash,
      handler: "index.handler",
      architectures: ["arm64"],
      memorySize: 1024,
      timeout: 1,
      loggingConfig: { logFormat: "JSON" },
    });
  }
}
